server:
  port: 8804

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/taibiex_private_api_v2?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: tabi
    password: tabi@2024
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 100
      auto-commit: true
      pool-name: XCarHikariCP
      max-lifetime: 3600000
      connection-timeout: 60000
      connection-test-query: SELECT 1
      transaction:
        rollback-on-commit-failure: true
      leak-detection-threshold: 3500000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  data:
    redis:
      port: 6379
      host: redis-cache-us-east1-2-bpqedb.serverless.use1.cache.amazonaws.com
      database: 2
      cluster:
        nodes: redis-cache-us-east1-2-bpqedb.serverless.use1.cache.amazonaws.com:6379
      ssl:
        enabled: true
      connect-timeout: 5000

tabiscan:
  api-domain:
    # NOTE: 不同环境的 api domain 地址可能不同，这里用于查询用户余额等功能
    url: https://tabiv2-test.tabiscan.com

app:
  subgraphs:
    endpoint: http://18.136.213.241:8000/subgraphs/name/tabiV2/uniswap-v3
